{
 "title": "App Stats",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } }
  ]
 },
 "panels": [
  {
   "title": "Total Cpu",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(node_cpu_seconds_total{mode!=\"idle\"})/sum(node_cpu_seconds_total) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "((sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes)) / sum(node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU(namespace)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{pod!=\"\", cpu=\"total\"}[5m]))  / scalar(sum(rate(node_cpu_seconds_total[5m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory(namespace)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sort_desc(sum by(pod) (container_memory_usage_bytes{pod!=\"\", namespace=~\"$namespace\", container!=\"\"})) / scalar(machine_memory_bytes)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Users Created",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "sum by(test_user) (user_created{test_user=\"true\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(test_user) (user_created{test_user=\"false\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}