{
 "title": "Test Result",
 "description": "k6 Test Result",
 "tags": [
  "prometheus",
  "k6"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "testid", "query": { "query": "label_values(testid)" } },
   { "name": "scenario", "query": { "query": "label_values(scenario)" } },
   {
    "name": "type",
    "query": {
     "query": "label_values({__name__=~\"k6.*\",testid=~\"$testid\"}, type)"
    }
   },
   { "name": "url", "query": { "query": "label_values(url)" } },
   { "name": "Filters" },
   {
    "name": "metrics",
    "query": "k6_http_req_waiting_seconds, k6_http_req_duration_seconds"
   },
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "VUS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(testid) (k6_vus{testid=~\"$testid\"})",
     "legendFormat": "Total vus  - {{testid}}"
    },
    {
     "expr": "k6_vus{testid=~\"$testid\"}",
     "legendFormat": "Active VUs   - {{testid}}"
    }
   ]
  },
  {
   "title": "Score",
   "type": "timeseries",
   "gridPos": { "h": 20, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "avg by(testid, type) (avg_over_time(k6_score_gauge{testid=~\"$testid\", type=~\"$type\"}[1m]))",
     "legendFormat": "avg[1m]: {{testid}} = {{type}}"
    },
    {
     "expr": "avg by(testid) (avg_over_time(k6_score_gauge{testid=~\"$testid\", type=~\"$type\"}[1m]))",
     "legendFormat": "full avg[1m]: {{testid}}"
    },
    {
     "expr": "avg by(testid) (k6_score_trend_avg{testid=~\"$testid\", type=~\"$type\"})",
     "legendFormat": "full avg: {{testid}}"
    }
   ]
  },
  {
   "title": "Match Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(k6_match_success_rate{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ready Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(k6_ready_success_rate{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Established Rate",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(k6_established_success_rate{testid=~\"$testid\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Match Elapsed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "avg by(testid) (k6_match_elapsed_avg{testid=~\"$testid\", type=~\"$type\"})",
     "legendFormat": "match avg: {{testid}}"
    },
    {
     "expr": "avg (k6_match_elapsed_p90{testid=~\"$testid\", type=~\"$type\"}) by(testid)",
     "legendFormat": "match p90: {{testid}}"
    },
    {
     "expr": "avg (k6_match_elapsed_p99{testid=~\"$testid\", type=~\"$type\"}) by(testid)",
     "legendFormat": "match p99: {{testid}}"
    }
   ]
  },
  {
   "title": "Established  + Ready",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "avg(k6_established_elapsed_avg{testid=~\"$testid\"}) by (testid)",
     "legendFormat": "established avg: {{testid}}"
    },
    {
     "expr": "avg(k6_established_elapsed_p90{testid=~\"$testid\"}) by (testid)",
     "legendFormat": "established p90: {{testid}}"
    },
    {
     "expr": "avg(k6_ready_elapsed_avg{testid=~\"$testid\"}) by (testid)",
     "legendFormat": "ready avg: {{testid}}"
    },
    {
     "expr": "avg(k6_ready_elapsed_p90{testid=~\"$testid\"}) by (testid)",
     "legendFormat": "ready p90: {{testid}}"
    }
   ]
  },
  {
   "title": "Checks",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "k6_checks_rate{testid=~\"$testid\"}"
    }
   ]
  },
  { "title": "Performance Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "Requests Made",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "expr": "sum by(testid) (k6_http_reqs_total{testid=~\"$testid\"})",
     "legendFormat": "{{testid}} -"
    }
   ]
  },
  {
   "title": "HTTP Failures",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 4, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "reqs" } },
   "targets": [
    {
     "expr": "sum by(testid) (k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"})",
     "legendFormat": "{{testid}} -"
    }
   ]
  },
  {
   "title": "Peak RPS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum by(testid) (irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "{{testid}}  -"
    }
   ]
  },
  {
   "title": "P95 Response Time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(testid) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "{{testid}}  -"
    }
   ]
  },
  {
   "title": "Data Received",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(testid) (k6_data_received_total{testid=~\"$testid\"})",
     "legendFormat": "{{testid}}  -"
    }
   ]
  },
  {
   "title": "Data Sent",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(testid) (k6_data_sent_total{testid=~\"$testid\"})",
     "legendFormat": "{{testid}} -"
    }
   ]
  },
  {
   "title": "Iteration",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(testid) (k6_iterations_total{testid=~\"$testid\"})",
     "legendFormat": "{{testid}} -"
    }
   ]
  },
  {
   "title": "Data flow",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 9, "x": 4, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "avg by(testid)(sum by(testid)(irate(k6_data_received_total{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "Received - {{testid}}"
    },
    {
     "expr": "avg by(testid)(sum by(testid)(irate(k6_data_sent_total{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "Sent - {{testid}}"
    }
   ]
  },
  {
   "title": "Code Status Rate",
   "type": "stat",
   "gridPos": { "h": 10, "w": 11, "x": 13, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 * (sum by(status, testid) (k6_http_reqs_total{testid=~\"$testid\"}) / on() group_left() sum(k6_http_reqs_total{testid=~\"$testid\"}) )",
     "legendFormat": "{{status}} - {{testid}}"
    }
   ]
  },
  {
   "title": "Dropped Iteration ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(testid) (k6_dropped_iterations_total{testid=~\"$testid\"})",
     "legendFormat": "{{testid}} -"
    }
   ]
  },
  { "title": "Thresholds WIP", "type": "table", "gridPos": { "h": 7, "w": 11, "x": 13, "y": 59 } },
  {
   "title": "HTTP ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 66 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Requests by URL",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "k6_http_reqs_total{testid=~\"$testid\"}"
    },
    {
     "expr": "histogram_quantile(0, sum by(name) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(name) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(name) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))"
    },
    {
     "expr": "histogram_quantile(1, sum by(name) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))"
    }
   ]
  },
  {
   "title": "HTTP breakdown",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by(testid)(histogram_sum(rate(k6_http_req_blocked_seconds{testid=~\"$testid\", name=~\"$url\",scenario=~\"$scenario\"}[$__rate_interval]))\n/\nhistogram_count(rate(k6_http_req_blocked_seconds{testid=~\"$testid\", name=~\"$url\",scenario=~\"$scenario\"}[$__rate_interval])))",
     "legendFormat": "Blocked - {{testid}}"
    },
    {
     "expr": "avg by(testid)(histogram_sum(rate(k6_http_req_connecting_seconds{testid=~\"$testid\", name=~\"$url\",scenario=~\"$scenario\"}[$__rate_interval]))\n/\nhistogram_count(rate(k6_http_req_connecting_seconds{testid=~\"$testid\", name=~\"$url\",scenario=~\"$scenario\"}[$__rate_interval])))",
     "legendFormat": "Connecting - {{testid}}"
    },
    {
     "expr": "avg by(testid)(histogram_sum(rate(k6_http_req_duration_seconds{testid=~\"$testid\", name=~\"$url\",scenario=~\"$scenario\"}[$__rate_interval]))\n/\nhistogram_count(rate(k6_http_req_duration_seconds{testid=~\"$testid\", name=~\"$url\",scenario=~\"$scenario\"}[$__rate_interval])))",
     "legendFormat": "Duration - {{testid}}"
    },
    {
     "expr": "avg by(testid)(histogram_sum(rate(k6_http_req_receiving_seconds{testid=~\"$testid\", name=~\"$url\",scenario=~\"$scenario\"}[$__rate_interval]))\n/\nhistogram_count(rate(k6_http_req_receiving_seconds{testid=~\"$testid\", name=~\"$url\",scenario=~\"$scenario\"}[$__rate_interval])))",
     "legendFormat": "Receiving - {{testid}}"
    },
    {
     "expr": "avg by(testid)(histogram_sum(rate(k6_http_req_sending_seconds{testid=~\"$testid\", name=~\"$url\",scenario=~\"$scenario\"}[$__rate_interval]))\n/\nhistogram_count(rate(k6_http_req_sending_seconds{testid=~\"$testid\", name=~\"$url\",scenario=~\"$scenario\"}[$__rate_interval])))",
     "legendFormat": "Sending - {{testid}}"
    },
    {
     "expr": "avg by(testid)(histogram_sum(rate(k6_http_req_tls_handshaking_seconds{testid=~\"$testid\", name=~\"$url\",scenario=~\"$scenario\"}[$__rate_interval]))\n/\nhistogram_count(rate(k6_http_req_tls_handshaking_seconds{testid=~\"$testid\", name=~\"$url\",scenario=~\"$scenario\"}[$__rate_interval])))",
     "legendFormat": "TLS Handshaking - {{testid}}"
    },
    {
     "expr": "avg by(testid)(histogram_sum(rate(k6_http_req_waiting_seconds{testid=~\"$testid\", name=~\"$url\",scenario=~\"$scenario\"}[$__rate_interval]))\n/\nhistogram_count(rate(k6_http_req_waiting_seconds{testid=~\"$testid\", name=~\"$url\",scenario=~\"$scenario\"}[$__rate_interval])))",
     "legendFormat": "Waiting - {{testid}}"
    }
   ]
  },
  {
   "title": "Scenarios",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 87 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(testid)(rate(k6_http_req_duration_seconds{scenario=~\"$scenario\", expected_response=\"true\", testid=~\"$testid\"}[$__rate_interval])))"
    },
    {
     "expr": "sum by(scenario) (max(k6_http_reqs_total{testid=~\"$testid\", scenario=~\"$scenario\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(scenario) (sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(scenario) (k6_iterations_total{testid=~\"$testid\",scenario=~\"$scenario\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(scenario) ( k6_http_reqs_total{testid=~\"$testid\",scenario=~\"$scenario\",expected_response=\"false\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scenario level metrics $testid $scenario",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 94 },
   "repeat": "scenario",
   "targets": [
    {}
   ]
  },
  {
   "title": "Scenarios",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(testid)(rate(k6_http_req_duration_seconds{scenario=~\"$scenario\", expected_response=\"true\", testid=~\"$testid\"}[$__rate_interval])))"
    },
    {
     "expr": "sum by(scenario) (max(k6_http_reqs_total{testid=~\"$testid\", scenario=~\"$scenario\"}))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by(scenario) (sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(scenario) (k6_iterations_total{testid=~\"$testid\",scenario=~\"$scenario\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(scenario) ( k6_http_reqs_total{testid=~\"$testid\",scenario=~\"$scenario\",expected_response=\"false\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 102 },
   "targets": [
    {
     "expr": "k6_vus{testid=~\"$testid\"}",
     "legendFormat": "Active VUs   - {{testid}}"
    },
    {
     "expr": "sum by(testid) (rate(k6_http_reqs_total{testid=~\"$testid\",scenario=~\"$scenario\"}[$__rate_interval]))",
     "legendFormat": "Requests Rate   - {{testid}}"
    },
    {
     "expr": "avg by(testid) (sum by(testid) (rate(k6_http_reqs_total{testid=~\"$testid\",scenario=~\"$scenario\", expected_response=\"false\"}[$__rate_interval])))",
     "legendFormat": "Failed Requests Rate  - {{testid}}"
    },
    {
     "expr": "(histogram_sum(rate(k6_http_req_duration_seconds{testid=~\"$testid\",scenario=~\"$scenario\"}[$__rate_interval]))\n/\nhistogram_count(rate(k6_http_req_duration_seconds{testid=~\"$testid\",scenario=~\"$scenario\"}[$__rate_interval]))) ",
     "legendFormat": "Response  Time (avg)  - {{testid}}"
    }
   ]
  }
 ]
}