windows:
	flutter build windows

chrome:
	flutter run -d chrome

chrome-prod:
	flutter run -d chrome


prod:
	flutter run --dart-define="SOCKET_ADDRESS=https://react-video-call-fjutjsrlaa-uc.a.run.app"



