# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :beta do

    puts "Starting beta"


    match(type: "appstore", readonly: true)

    puts "Finished match"


    build_app(
      # skip_build_archive: true,
      # archive_path: "../build/ios/archive/Runner.xcarchive",
    )



    # sh 'flutter build ipa --no-codesign'

    # sh 'flutter build ipa --dart-define="SOCKET_ADDRESS=https://react-video-call-fjutjsrlaa-uc.a.run.app"'

    # firebase_app_distribution(
    #       app: "1:619217777312:ios:c2e305e9e4d2ca8fd0cfc5",
    #       ipa_path: "../ios/Runner.ipa",
    #       testers: "andrewdelph@live.ca"
    #   )

    # add actions here: https://docs.fastlane.tools/actions
  end
end
