FROM grafana/grafana:9.3.2


COPY dashboards /data/grafana/provisioning/dashboards
COPY datasources /data/grafana/provisioning/datasources
COPY copyfiles.sh /script/copyfiles.sh

# RUN chmod 777 /script/copyfiles.sh



